src/Catcher Website/Catcher WebAPI/Catcher WebAPI/Controllers/EmployeeManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Catcher_WebAPI.Data.CanvasData;
using Catcher_WebAPI.Models.Tables;
using Microsoft.AspNetCore.Authorization;

namespace Catcher_WebAPI.Areas.APITester
{
    [Authorize]
    public class EmployeeManagementController : Controller
    {
        private readonly GoCanvasDbContext _context;

        public EmployeeManagementController(GoCanvasDbContext context)
        {
            _context = context;
        }

        // GET: APITester/Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: APITester/Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblEmployee = await _context.Employees
                .FirstOrDefaultAsync(m => m.LineID == id);
            if (tblEmployee == null)
            {
                return NotFound();
            }

            return View(tblEmployee);
        }

        // GET: APITester/Employees/Create
        public IActionResult Create()
        {
            var locations = _context.Locations.Select(s => s);
            List<string> locationsAsString = locations.Select(l => l.Location).ToList();
            CatchWatchEmployee.AvailableLocationsAsStrings = locationsAsString;

            return View();
        }

        // POST: APITester/Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("LineID,BadgeID,FirstName,LastName,Username,Location,Active,Suspended")] CatchWatchEmployee CatchWatchEmployee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(CatchWatchEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(CatchWatchEmployee);
        }

        // GET: APITester/Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var locations = _context.Locations.Where(s=>!string.IsNullOrWhiteSpace(s.Location)).Select(s => s);
            if (locations.Any())
            {
                List<SelectListItem> locationsAsSelectListItems = new List<SelectListItem>();

                foreach (CatchWatchLocations location in locations)
                {
                    locationsAsSelectListItems.Add(new SelectListItem(location.Location, location.Location));
                }

                ViewBag.LocationsAsSelectListItems = locationsAsSelectListItems;
                ViewBag.Locations = locations.ToList();
            }

            var tblEmployee = await _context.Employees.FindAsync(id);
            if (tblEmployee == null)
            {
                return NotFound();
            }
            return View(tblEmployee);
        }

        // POST: APITester/Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("LineID,BadgeID,FirstName,LastName,Username,Location,Active,Suspended")] CatchWatchEmployee CatchWatchEmployee)
        {
            if (id != CatchWatchEmployee.LineID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(CatchWatchEmployee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!tblEmployeeExists(CatchWatchEmployee.LineID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(CatchWatchEmployee);
        }

        // GET: APITester/Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            return NotFound();
        }

        // POST: APITester/Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            return RedirectToAction(nameof(Index));
        }

        private bool tblEmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.LineID == id);
        }
    }
}

src/Catcher Website/Catcher WebAPI/Catcher WebAPI/Controllers/SystemControlController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Catcher_WebAPI.Data.CanvasData;
using Catcher_WebAPI.Models.Tables;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using RestSharp.Extensions;

namespace Catcher_WebAPI.Areas.APITester.Controllers
{
    public class SystemControlController : Controller
    {
        private readonly GoCanvasDbContext _context;

        public SystemControlController(GoCanvasDbContext context)
        {
            _context = context;
        }
        // GET: SystemControlController
        [HttpGet]
        public ActionResult Index()
        {
            if (!_context.SystemControls.Any())
            {
                _context.SystemControls.Add(new SystemControl() {Status = 0});
                _context.SaveChanges();
            }
            
            ViewBag.Status = _context.SystemControls.First().Status;
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "SuperUser")]
        public ActionResult Index(int ManualSetStatusTo)
        {
            string tblName = typeof(SystemControl).GetAttribute<TableAttribute>().Name;
            if (Request.Form["toggle"] == "0")
            {
                _context.Database.ExecuteSqlRaw($"UPDATE [{tblName}] SET [Status] = 1");
            }
            else
            {
                _context.Database.ExecuteSqlRaw($"UPDATE [{tblName}] SET [Status] = 0");
            }

            _context.SaveChanges();
            _context.SystemControls.Load();
            var systemState = _context.SystemControls.First();
            ViewBag.Status = systemState.Status;
            return View();
        }

        //// GET: SystemControlController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        //// GET: SystemControlController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: SystemControlController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: SystemControlController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: SystemControlController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: SystemControlController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: SystemControlController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

src/Catcher Website/Catcher WebAPI/Catcher WebAPI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using Catcher_WebAPI.Models.Tables
@inject SignInManager<tblUser> SignInManager
@inject UserManager<tblUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Catch Watch</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Catch Watch</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    @if (SignInManager.IsSignedIn(User) && await UserManager.IsInRoleAsync(await UserManager.GetUserAsync(User), "SuperUser"))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="APITester" asp-controller="APITester" asp-action="Index">API Tester</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SystemControl" asp-action="Index">System Control</a>
                        </li>
                     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeManagement" asp-action="Index">User Management</a>
                        </li>
                         }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SystemControl" asp-action="Index">System Status</a>
                        </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Catch Watch - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>